spring:
  application:
    name: QUIZ-SERVICE

  cloud:
    function:
      definition: acknowledgeInformation
      web:
        path: "/functions"

    stream:
      bindings:
        quizCreatedBinding-out-0:
          destination: quiz-created
          group: ${spring.application.name}
        acknowledgeInformation-in-0:
          destination: acknowledge-quiz
          group: ${spring.application.name}

  profiles:
    active: dev

  config:
    import: configserver:http://localhost:9094

  data:
    mongodb:
      uri: mongodb://localhost:27017/quizdb

  #rabbit mq configurations

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s

server:
  port: 9092

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


